server:
    port: 8090

logging:
    level:
        org.springframework.web: DEBUG
spring:
    datasource:
        url: jdbc:mysql://localhost/emazon_stock
        username: ${stock_user}
        password: ${stock_password}
    jpa:
        hibernate:
            ddl-auto: update
