server:
    port: 8090

logging:
    level:
        org.springframework.web: DEBUG
spring:
    datasource:
        url: jdbc:mysql://localhost/emazon_stock
        username: "admin"
        password: "1007Admin@236176"
    jpa:
        hibernate:
            ddl-auto: update
